""" An init file for vim and nvim

syntax on

" Mysterious fix to prevent linux term from going into Replace mode
" https://superuser.com/questions/1284561/why-is-vim-starting-in-replace-mode
set t_u7=

" linux_config vim runtimepath
set runtimepath+=~/linux_config/vim
" Plugins
set runtimepath+=~/linux_config/vim-plugins/ctrlp

" Change leader key
nnoremap <SPACE> <Nop>
let mapleader = " "

set shell=/bin/bash

" Allow windows to unsaved buffers to be closed
set hidden

" Disable mouse support
set mouse=

" Disable swap files because they are annoying. A better solution might be to make a swap file directory in the home dir or something
set noswapfile

" Disable read-only: This is to prevent vimdiff from opening in readonly mode
set noro

" Status line
set laststatus=2  " Always show status line
hi StatusLine ctermbg=White ctermfg=DarkGrey

" Line length: Highlight 80th character on the line
"hi ColorColumn ctermbg=LightGrey ctermfg=White
"call matchadd('ColorColumn', '\%80v', 100)

" Put a line under the cursor
set cursorline
set cursorcolumn
"hi CursorColumn ctermbg=lightgrey ctermfg=black
" Bold the line number
"hi cursorLineNR cterm=bold

" I am a Company Man who uses spaces instead of tabs
set shiftwidth=2 tabstop=2 expandtab
"set smartindent
set autoindent
"set tabstop=3 noexpandtab

" Line numbers
set number

" Show trailing whitespace
"if &termencoding ==# 'utf-8' || &encoding ==# 'utf-8'
"let &listchars = "tab:»·,trail:\u2423,extends:\u21c9,precedes:\u21c7,nbsp:\u26ad"
let &listchars = "tab:»·,trail:\u2423"
set list
"endif

" Increase height of CtrlP search window
let g:ctrlp_match_window = 'min:1,max:55'
" Use vim pwd as root dir to search from in CtrlP
let g:ctrlp_working_path_mode = 0
" When using <C-z> and <C-o> to open multiple files, open them in background
let g:ctrlp_open_multiple_files = 'i'
" Regex paths to ignore
let g:ctrlp_custom_ignore = 'venv/'

" ctags configuration. From vim help:
"When a tag file name starts with "./", the '.' is replaced with the path of
"the current file.  This makes it possible to use a tags file in the directory
"where the current file is (no matter what the current directory is).  The idea
"of using "./" is that you can define which tag file is searched first: In the
"current directory ("tags,./tags") or in the directory of the current file
"("./tags,tags").
" This is set up to use root tags file, or look for "build" in hyper
set tags=tags,**/build/*/tags

"====    My  mapping changes:    ====
" * <C-k> and <C-j> scroll up and down the page
" * 9 moves cursor to beginning of the line
" * '<Leader>e' moves forward a word and 'w' moves back a word. I don't worry about start/end word boundries
" * 'b' is CtrlP buffer mode, 'h' is CtrlP search
" * <C-a> moves back 1/2 screen
" * <C-m>, <C-n> and <C-b> are cnext, cprevious, and copen, respectively
" * Q to enter Ex mode is disabled
"====  --------------------------------  ====

" Make vimdiff colors not awful
hi DiffAdd ctermbg=White ctermfg=22 cterm=reverse
hi DiffChange ctermbg=White ctermfg=57 cterm=reverse
hi DiffDelete ctermbg=White ctermfg=160 cterm=reverse
hi DiffText ctermbg=White ctermfg=Black cterm=reverse

" Insert newline without going to insert mode
nnoremap <CR> O

" Disable "Ex" mode
map Q <nop>

" netrw
nnoremap <Leader>e :Ex<CR>

" ctrlp shortcuts
nnoremap b :CtrlPBuffer<CR>
nnoremap B :CtrlP<CR>

" Some convenient buffer scrolling
nnoremap <C-k> 6<C-e>
nnoremap <C-k> 6<C-y>
vnoremap <C-j> 6<C-e>
vnoremap <C-k> 6<C-y>
" C-d is move up half screen, C-a is move down
"nnoremap <C-a> <C-u>
"vnoremap <C-a> <C-u>
" C-d is move down half screen, C-f is move up
nnoremap <C-f> <C-u>
vnoremap <C-f> <C-u>

nnoremap w b

nnoremap 9 $
vnoremap 9 $

" Moving between panes with C-u - C-p
nnoremap <C-u> <C-w>h
nnoremap <C-i> <C-w>j
nnoremap <C-o> <C-w>k
" A bit of a hack because CtrlP will rebind <C-p> after vimrc. This will set
"   the key binding after plugins load
autocmd VimEnter * nnoremap <C-p> <C-w>l

" Horizontal split
nnoremap <C-w>h <C-w>s

" When already in normal mode, 'esc' will call 'noh' (no highlighting), which
" clears the last highlight
nnoremap <esc> :noh<CR><esc>
